version: '3.1'

volumes:
  pgdata:


services:

  staying-organized-db:
    container_name: staying-organized-db
    image: postgres:latest
    restart: always
    ports:
      - "4432:5432"
    environment:
      - POSTGRES_DB=staying-organized
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5 

  staying-organized-api:
    container_name: staying-organized-api
    build: 
      context: .
    ports: 
      - "7770:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://staying-organized-db:5432/staying-organized
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    volumes: 
      - "/opt/staying-organized/files:/opt/files"
    depends_on:
      - staying-organized-db
